#!/bin/bash

# lmao dont judge me it works for me

while true; do
    tmux send-keys -t "%$1" '\./server |& logfilter' Enter
    sleep 0.1
    inotifywait -qq "server" -e MODIFY -e MOVE_SELF
    tmux send-keys -t "%$1" C-c
    echo "reloading..."
done
