#!/usr/bin/env bash

cd "${0%/*}"

set noglob

ORM_DB=db.sqlite
VERSION=0.0.1
IRC_SERVER_HOST=127.0.0.1
PORT=${PORT:-6667}

declare -A SUBS
# self explanatory
function query() {
  function _query() {
    local QUERY
    QUERY="$1"
    shift
    printf ".parameter init\n"
    INDEX=1
    for arg in "$@"; do
      : "${arg//\\/\\\\\\\\}"
      : "${_//$'\t'/    }"
      : "${_//\"/\\\"}"
      : "${_//\'/\\\'}"
      : "${_//$'\n'/\\\\n}"
      if [[ "$_" =~ "'" ]]; then
        printf ".parameter set ?%d \"%s\"\n" $INDEX "$_"
      else
        printf ".parameter set ?%d \"'%s'\"\n" $INDEX "$_"
      fi
      ((INDEX++))
    done
    printf "%s\n" "$QUERY";
  }
  sqlite3 -separator $'\t' "$ORM_DB" < <(_query "$@")
}

split() {
   # Usage: split "string" "delimiter"
   IFS=$'\n' read -d "" -ra arr <<< "${1//$2/$'\n'}"
}

function listen() {
  local TOPIC
  TOPIC="$1"
  if [[ -z "$TOPIC" ]]; then
    debug "ATTEMPTED TO LISTEN ON EMPTY TOPIC"
    return
  fi
  local -a arr
  while true; do
    IFS= read -r line < "$TOPIC"
    split "${line//$'\r'}" ' '
    if [[ "${arr[0]}" =~ :(.+) ]]; then
      PREFIX="${BASH_REMATCH[1]}"
      arr=("${arr[@]:1}")
    fi
    COMMAND="${arr[0]}"
    debug "LISTENED COMMAND: '$COMMAND'"
    arr=("${arr[@]:1}")

    case "$COMMAND" in
      PRIVMSG)
        [[ "${PREFIX%%@*}" == "$NICK" ]] && continue
        ;;
      JOIN)
        ;;
      *)
        continue
        ;;
    esac
    # forward the message
    printf "%s\n" "$line"
    debug "SENT: '${line//$'\r'/\\r}'"
  done
}

function subscribe() {
  mkdir -p pubsub/irc
  local tmppipe=$(mktemp -up pubsub/irc)
  mkfifo -m 600 "$tmppipe"
  SUBSCRIPTION="$tmppipe"
  debug "PIPE CREATED: $tmppipe"
}

function unsubscribe() {
  debug "PIPE CLOSING: $SUBSCRIPTION"
  rm -f "$SUBSCRIPTION"
  debug "PIPE CLOSED: $SUBSCRIPTION"
}

function broadcast() {
  [[ ! -d "pubsub/irc" ]] && return
  TEE_ARGS=$(find pubsub/irc -type p)
  [[ -z "$TEE_ARGS" ]] && return
  tee $TEE_ARGS > /dev/null
}

reply() {
  local RESPONSE
  printf -v "RESPONSE" ":%s %s\r\n" "$IRC_SERVER_HOST" "$*"
  RESPONSE="${RESPONSE:0:512}"
  printf "%s" "$RESPONSE"
  debug "REPLYING: $RESPONSE"
}

debug() {
  printf "%s\n" "$@" 1>&2
}

if [[ -z "$IRC_CONN_HANDLER" ]]; then

  rm -rf pubsub
  mkdir pubsub


  query 'CREATE TABLE IF NOT EXISTS channels
    (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name varchar(201)
    );'

  echo "i am the server" 1>&2
  echo -n "Starting server on port "

  export IRC_CONN_HANDLER=true
  export IRC_SERVER_CREATED="$(date)"
  tcpserver -1 -o -l 0 -H -R -c 1000 0 $PORT $0
else
  # echo "connection opened with $TCPREMOTEIP" 1>&2
  subscribe
  while IFS= read -r line; do
    split "${line//$'\r'}" ' '
    if [[ "${arr[0]}" =~ :(.+) ]]; then
      PREFIX="${BASH_REMATCH[1]}"
      debug "PREFIX: '$PREFIX'"
      arr=("${arr[@]:1}")
    fi
    COMMAND="${arr[0]}"
    debug "COMMAND: '$COMMAND'"
    arr=("${arr[@]:1}")
    case "${COMMAND^^}" in
      # CAP)
      #   CAP="${arr[0]}"
      #   reply CAP "* NAK :"
      #   ;;
      NICK)
        NICK="${arr[0]}"
        ;;
      USER)
        USER="${arr[0]}"
        MODE="${arr[1]}"
        REALNAME="${arr[3]}"
        reply 001 $NICK ":Welcome, $NICK!$USER@$IRC_SERVER_HOST"
        reply 002 $NICK ":Your host is $IRC_SERVER_HOST, running version $VERSION"
        reply 003 $NICK ":This server was created $IRC_SERVER_CREATED"
        reply 004 $NICK "$IRC_SERVER_HOST bash-$VERSION"
        reply 376 $NICK ":End of the /MOTD command."
        ;;
      PRIVMSG)
        TARGET="${arr[0]}"
        arr=("${arr[@]:1}")
        printf "%s\r\n" ":$NICK PRIVMSG $TARGET ${arr[*]}" | broadcast
        debug "FORWARDING MESSAGE TO $TARGET"

        ;;
      JOIN)
        if [[ "${arr[@]}" == "0" ]]; then
          debug "YOU LEFT, IDK WHAT TO DO"
        else
          CHANNELS="${arr[0]}"
          KEYS="${arr[1]}"
          split "$CHANNELS" ','
          CHANNELS=("${arr[@]}")
          split "$KEYS" ','
          KEYS=("${arr[@]}")
          for CHANNEL in ${CHANNELS[@]}; do
            if [[ "$CHANNEL" != "#test" ]]; then
              continue
            fi
            debug "$NICK joined $CHANNEL"
            SUBS["$CHANNEL"]=true
            listen "$SUBSCRIPTION" &
            printf "%s\r\n" ":$NICK!$USER@$IRC_SERVER_HOST JOIN :$CHANNEL" | broadcast
            reply 366 $NICK $CHANNEL :
          done
        fi
        ;;
      PING)
        reply PONG "$NICK" "${arr[0]}"
        ;;
      *)
        debug "UNRECOGNIZED COMMAND"
        debug "${arr[@]}"
        ;;
    esac
  done
  # echo "connection closed with $TCPREMOTEIP" 1>&2
  unsubscribe
fi
